name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  UnitTest:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Code
        uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Modules
        run: pnpm install
      - name: Run Unit Test
        run: pnpm test
      