name: deploy-doc
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout Code
        uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Modules
        run: pnpm install
      - name: Build Doc
        run: pnpm docs:build
      - name: deloy doc to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-dist
